CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
### LED ###
CONFIG_INDICATOR_LED_INTERVAL_MS=250
CONFIG_INDICATOR_LED_BATTERY_LEVEL_HIGH=50
CONFIG_INDICATOR_LED_BATTERY_LEVEL_CRITICAL=10
CONFIG_INDICATOR_LED_WIDGET=y
